### ISSUE TITLE
Problems on reservoir.py

### ISSUE THREAD

**Issue by giorgionanfa** [djsaunde/bindsnet_foolbox#1]
Hi, i would like to ask an information about a problem on Foolbox.
I tried to use Foolbox modified for BindsNET. Using Foolbox for reservoir.py,
i observed a problem relative to the model. I obtain the following error.
The fmodel has different dimensions compared to the ones of the image.
I can't change the parameters of the Logistic Regression, so i didn't find
a solution for this problem.
This is the code that i added to the previously existing reservoir.py for the test phase:

images=images.numpy()
images= images.astype('float32')
images /= 63.75    
fmodel = foolbox.models.PyTorchModel(model, bounds=(0, 1), num_classes=10)
attack = foolbox.attacks.CarliniWagnerL2Attack(fmodel)
adversarial = attack(images[1], labels[1])

print('adversarial class', np.argmax(fmodel.predictions(adversarial)))

This is the error:

Traceback (most recent call last):
  File "res_fool.py", line 176, in <module>
    adversarial = attack(images[1], labels[1])
  File "/home/giorgio/anaconda3/envs/gioenv/lib/python3.6/site-packages/foolbox/attacks/base.py", line 124, in wrapper
    distance=distance, threshold=threshold)
  File "/home/giorgio/anaconda3/envs/gioenv/lib/python3.6/site-packages/foolbox/adversarial.py", line 87, in __init__
    self.predictions(original_image)
  File "/home/giorgio/anaconda3/envs/gioenv/lib/python3.6/site-packages/foolbox/adversarial.py", line 306, in predictions
    predictions = self.__model.predictions(image)
  File "/home/giorgio/anaconda3/envs/gioenv/lib/python3.6/site-packages/foolbox/models/base.py", line 160, in predictions
    return np.squeeze(self.batch_predictions(image[np.newaxis]), axis=0)
  File "/home/giorgio/anaconda3/envs/gioenv/lib/python3.6/site-packages/foolbox/models/pytorch.py", line 88, in batch_predictions
    predictions = self._model(images)
  File "/home/giorgio/anaconda3/envs/gioenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "res_fool.py", line 102, in forward
    out = self.linear(x.float())
  File "/home/giorgio/anaconda3/envs/gioenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/giorgio/anaconda3/envs/gioenv/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/giorgio/anaconda3/envs/gioenv/lib/python3.6/site-packages/torch/nn/functional.py", line 1026, in linear
    output = input.matmul(weight.t())
RuntimeError: size mismatch, m1: [28 x 28], m2: [625 x 10] at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/generic/THCTensorMathBlas.cu:249

Thank you so much,
Giorgio

**Comment by djsaunde** [comment]
Hi @giorgionanfa, I don't really know the answer to your question. This package was modified for a single experiment in our lab that we never ended up doing, so I don't expect it to work. I suggest you try to implement the functionality you want yourself. I apologize that I can't be more helpful.
